Close #2 - Set up check list router
ss-ita/checklisty-web pull request #13
Opened 2019-01-31 10:27 UTC by machikharostyk

2019-01-31 11:03 UTC, Antoniozinchenko requested changes

2019-01-31 11:03 UTC, Antoniozinchenko commented on package.json
> +    "create-react-app": "^2.1.3",
why do you need it as additional dependency??

2019-01-31 11:03 UTC, Antoniozinchenko commented on src/components/main/MainPage.jsx
> +    componentWillMount(){
dont use componentWillMount
use componentDidMount instead

2019-01-31 11:03 UTC, Antoniozinchenko commented on src/components/main/MainPage.jsx
> +                    <div style={{display:'flex', flexDirection:'column'}}>
don't write inline styles
add styles to .css

2019-01-31 11:03 UTC, Antoniozinchenko commented on src/components/main/ShowCheckList.jsx
> +    componentWillMount(){
dont use componentWillMount
use componentDidMount instead

2019-01-31 11:03 UTC, Antoniozinchenko commented on src/components/main/ShowCheckList.jsx
> +        const getTitle = typeList.filter(elem => elem.id === id);
use **find** instead of **filter** method and move this logic to componentDidMount (will be changed when backend will be implemented)

2019-01-31 14:50 UTC, machikharostyk commented on package.json
> +    "create-react-app": "^2.1.3",
It was created automatically, should i remove it?

2019-01-31 15:06 UTC, Antoniozinchenko commented on package.json
> +    "create-react-app": "^2.1.3",
Yes

2019-01-31 15:06 UTC, Antoniozinchenko commented on package.json
> +    "create-react-app": "^2.1.3",
Yes

2019-02-01 12:24 UTC, rostyslav-vasyliuk approved these changes

2019-02-01 12:25 UTC, romanolytvyn approved these changes

2019-02-01 12:27 UTC, Yuri-Pristay approved these changes

2019-02-01 12:27 UTC, Roman6917 approved these changes

2019-02-01 12:28 UTC, OBats approved these changes

2019-02-01 12:38 UTC, Antoniozinchenko approved these changes

2019-02-01 12:52 UTC, merged