Fix search and rewrite component
ss-ita/checklisty-web pull request #168
Opened 2019-03-13 09:59 UTC by machikharostyk

2019-03-13 11:27 UTC, AndriyTykhan approved these changes

2019-03-13 11:59 UTC, rostyslav-vasyliuk approved these changes

2019-03-13 12:06 UTC, Yuri-Pristay approved these changes

2019-03-13 12:26 UTC, Antoniozinchenko requested changes

2019-03-13 12:26 UTC, Antoniozinchenko commented on src/components/main/mainContent/MainPage.jsx
> +  function usePrevious(value) {
custom hook inside component detach it

2019-03-13 12:26 UTC, Antoniozinchenko commented on src/components/main/mainContent/MainPage.jsx
> +  }, [activePage, totalPage]);
write custom hook for this and detach even from this file

2019-03-13 12:26 UTC, Antoniozinchenko commented on src/components/main/mainContent/SearchBar.jsx
> +  const textInput = React.createRef();
why use ref instead of state?

2019-03-19 10:33 UTC, romanolytvyn approved these changes

2019-03-22 09:21 UTC, closed without merging