Closes #18 - Create basic markup for auth and setup sending data from forms to server
ss-ita/checklisty-web pull request #19
Opened 2019-01-31 19:28 UTC by romanolytvyn

2019-01-31 19:41 UTC, OBats approved these changes

2019-02-01 11:22 UTC, rostyslav-vasyliuk approved these changes

2019-02-01 11:51 UTC, Yuri-Pristay approved these changes

2019-02-01 15:01 UTC, Antoniozinchenko requested changes
Need implement Formik usage and http layer with axios

2019-02-04 17:27 UTC, closed without merging