Checklist View Creation
ss-ita/checklisty-web pull request #32
Opened 2019-02-05 15:42 UTC by rostyslav-vasyliuk

2019-02-05 16:04 UTC, Antoniozinchenko requested changes

2019-02-05 16:04 UTC, Antoniozinchenko commented on src/components/checklist/SingleChecklistItem.jsx
> +    componentWillMount() {
do not use componentWillMount use componentDidMount instead

2019-02-05 16:04 UTC, Antoniozinchenko commented on src/components/checklist/SingleChecklistItem.jsx
> +        if (this.state.data.priority === 0) {
create const array with colors and labels instead conditions and don't set it in lifecycle hook at all 
example: 
`const priorities = [
  { color: 'green', label: 'Low'},
  { color: 'yellow', label: 'Medium'},
  { color: 'red', label: 'High'},
]`
in render: 
`<Icon name="circle" size="tiny" 
color={priorities[data.priority].color} 
className={style.priorityCircle} />`

2019-02-06 08:05 UTC, Antoniozinchenko approved these changes

2019-02-06 11:20 UTC, machikharostyk approved these changes

2019-02-06 14:06 UTC, Roman6917 approved these changes

2019-02-06 17:50 UTC, AndriyTykhan approved these changes

2019-02-06 19:51 UTC, romanolytvyn approved these changes

2019-02-06 19:53 UTC, merged