Closes #25 - implement component for avatar upload (Front-end )
ss-ita/checklisty-web pull request #65
Opened 2019-02-13 18:19 UTC by Roman6917

2019-02-13 20:09 UTC, rostyslav-vasyliuk approved these changes

2019-02-14 08:27 UTC, Antoniozinchenko requested changes

2019-02-14 08:27 UTC, Antoniozinchenko commented on package.json
> +	"name": "check-list",
indent using spaces 2

2019-02-14 10:39 UTC, Antoniozinchenko approved these changes

2019-02-14 11:05 UTC, Yuri-Pristay approved these changes

2019-02-14 11:13 UTC, romanolytvyn approved these changes

2019-02-14 11:21 UTC, anzhelikavelychko approved these changes

2019-02-14 11:23 UTC, merged