Closes #67 - Add modal for unsigned user
ss-ita/checklisty-web pull request #68
Opened 2019-02-14 11:09 UTC by rostyslav-vasyliuk

2019-02-14 11:13 UTC, romanolytvyn approved these changes

2019-02-14 12:07 UTC, Antoniozinchenko requested changes
why do you implement it without redux?
have two different modals inside component also not good
should separate code logic

2019-02-14 15:07 UTC, rostyslav-vasyliuk commented
@Antoniozinchenko 
1. There is issue with semantic cause it doesnt want to send and receive props between main component and separate component with modal. So thats the solution with changing content which depends on property 'isUserLogged'.
2. Redux will be used after it implementation.

2019-02-15 10:26 UTC, Antoniozinchenko approved these changes

2019-02-15 14:14 UTC, AndriyTykhan approved these changes

2019-02-15 14:15 UTC, OBats approved these changes

2019-02-15 14:15 UTC, machikharostyk approved these changes

2019-02-15 14:16 UTC, merged