Closes #53 - Stylize header (with navbar) and Intro section
ss-ita/checklisty-web pull request #69
Opened 2019-02-14 11:10 UTC by romanolytvyn

2019-02-14 12:02 UTC, Antoniozinchenko requested changes

2019-02-14 12:02 UTC, Antoniozinchenko commented on src/components/navbar/NavBar.jsx
> +import { Link, NavLink } from 'react-router-dom'; import { Menu, Dropdown, Icon } from 'semantic-ui-react';
move to different lines

2019-02-14 12:44 UTC, romanolytvyn commented on src/components/navbar/NavBar.jsx
> +import { Link, NavLink } from 'react-router-dom'; import { Menu, Dropdown, Icon } from 'semantic-ui-react';
@Antoniozinchenko already fixed

2019-02-14 14:29 UTC, rostyslav-vasyliuk approved these changes

2019-02-14 14:30 UTC, Roman6917 approved these changes

2019-02-14 14:31 UTC, machikharostyk approved these changes

2019-02-14 14:32 UTC, AndriyTykhan approved these changes

2019-02-14 16:02 UTC, anzhelikavelychko approved these changes

2019-02-15 09:30 UTC, Antoniozinchenko approved these changes

2019-02-15 09:57 UTC, merged