Set data into redux store
ss-ita/checklisty-web pull request #72
Opened 2019-02-14 13:00 UTC by angelikaSemeniuk

Set up redux, and store user data from the Sign In/ Sign out form

2019-02-14 13:02 UTC, romanolytvyn approved these changes

2019-02-14 13:02 UTC, rostyslav-vasyliuk approved these changes

2019-02-14 13:03 UTC, machikharostyk approved these changes

2019-02-14 13:07 UTC, OBats approved these changes

2019-02-14 13:59 UTC, Antoniozinchenko requested changes

2019-02-14 13:59 UTC, Antoniozinchenko commented on src/Routes.jsx
> +  userData: user.userData,
connect userData directly to NavBar, not in this component

2019-02-14 13:59 UTC, Antoniozinchenko commented on src/api/auth-api.js
> +  localStorage.setItem('access-token', response.data);
set the same as you write for signup
https://github.com/ss-ita/checklisty-web/pull/72/files#diff-e5d25ccf9ac553f2edda20e2eded5676R11

2019-02-14 13:59 UTC, Antoniozinchenko commented on package.json
> +    "redux-logger": "^3.0.6",
not used module, should be removed

2019-02-14 13:59 UTC, OBats approved these changes

2019-02-14 14:07 UTC, Antoniozinchenko requested changes

2019-02-14 14:07 UTC, Antoniozinchenko commented on src/components/auth/SignOut.jsx
> +    dispatch(handleLogOut());
this action should be dispatched on button click, not on component did mount. remove this component at all

2019-02-15 08:34 UTC, Antoniozinchenko requested changes

2019-02-15 08:34 UTC, Antoniozinchenko commented on src/Routes.jsx
> +/* eslint-disable react/prefer-stateless-function */
of course  it should be stateless! write Routes as simple functional component

2019-02-15 12:08 UTC, Antoniozinchenko approved these changes

2019-02-15 12:18 UTC, merged